identidock:
  build: .
  ports:
   - "80:9090"
   - "9191:9191"
   - "3000:3000"
  environment:
    ENV: PROD 
  volumes:
    - ./app:/app
  links:
    - dnmonster
    - redis
    - grafana

dnmonster:
  image: amouat/dnmonster:1.0

redis:
  image: redis:3.0

grafana:
  image: grafana/grafana

influxdb:
  image: influxdb

telegraf:
  image: telegraf